[RBT-274] Move TIFF header parsing, fix next-IFD
uploadcare/Piexif pull request #5
Opened 2022-01-24 09:44 UTC by mikhail-iurkov

## Description

Issue https://uploadcare.atlassian.net/browse/RBT-274

Also some code cleanup

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-01-24 10:30 UTC, homm requested changes

2022-01-24 10:30 UTC, homm commented on piexif/_load.py
> +    exifReader = _ExifReader.from_image(input_data)
Получается то, что не касается конкретно парсинга exif (разбор jpeg) спрятано в классе _ExifReader, а то, что касается (разные ifd) где-то снаружи. Не хочешь поменять?

2022-01-24 10:38 UTC, mikhail-iurkov commented on piexif/_load.py
> +    exifReader = _ExifReader.from_image(input_data)
Тут скорее идея, что `_ExifReader` парсит TIFF, а `from_image` позволяет этот TIFF извлечь (в том числе) из JPEG.

Может стоит ExifReader переименовать в TiffReader.

2022-01-24 11:52 UTC, homm requested changes

2022-01-24 11:52 UTC, homm commented on piexif/_load.py
> +            raise InvalidImageDataError("TIFF too short")
Для нас тут получаются точно такие же сообщения в ролбар, что и до этого. Давай тут оставим исключение, но в конце `from_image` чекнем размер ещё раз и не будем вызывать конструктор.

2022-01-24 11:52 UTC, homm commented on tests/s_test.py
> +        input = b'Exif\x00\x00II*\x00\x08\x00\x00\x00'
Добавь плиз больше вариантов обрезанных исходных данных, возвращающих пустой exif

2022-01-24 11:52 UTC, homm commented on piexif/_load.py
> +    exifReader = _ExifReader.from_image(input_data)
Давай в другом PR тогда

2022-02-01 09:43 UTC, homm approved these changes

2022-02-01 09:43 UTC, homm commented on tests/s_test.py
> +import pytest
unused

2022-02-01 09:48 UTC, merged